theme: jekyll-theme-minimal

title: Zahid Hasan
description: Zahid Hasan CV

logo: https://lh3.googleusercontent.com/LI-j-C_zjvLMyZt8aQPAK4Yd3__z5bBhInaQ-ZZmcWlW9f0qx9evQu0Bt7EspU2DCSs7rXOin45ZAVYopZ5IHQsTXsoKNCU_nrd27-t1PJJUsLJbSpOIS8tSpC0R4nuhXD1OrfhQ6a3vq-B4BJwCMSLC1U9LK7fncN3j6zWLjGDliYx6f3Ev_FCydq8S7qiZRsAQdHbxxdcugDbyWSCOfVdLodMtNWQaxfF33yGH44XKYdaljOwLYLQTyFYhyvtOzmnjTSQtDqA_HI4YLZPoPAKAGQ_KTAC_RKCO-QymtF2F21Qdh-p6qOWBS3qxaH1ZkR6IZnHmNt89RRVdV9JkXm97xNxrlIS9kQ1jtTeYgOkCUIVt7yXkd6fw7FKJsyKo9-9MMRZT827aVkrUE8HdQxzaez9VipPG9oMg_n36qNgjxw5BNIddQ61T9_BDeSwspWEAY8Lcs45R3LBTf7wE4Zg7CAnE2sMgNJfSb_iWcRON1JEwMAldsHyOiDLm2_Zp5GC-YQafaYXODpUd38BwKLa7i1nb174eL_5fLKu0TmKin3G1sf7gZ8jHAUyf-8M0q2p7LHGaA1BuDJ-_P_pvMDF28HHOXYIhuLHF5ICWPn14PpUGHLWxmNKam7hU8lY9SVIsnn9HdFIbip_4K5q0IYSaTANIFezLhNj018Lx2P00BhhYnDKu-GFJwl-DYQ-_qqu_hqj8Nb3C5VCm_m4-L8NPGISxQZJEz3OQOBnnUGJeRFH68mh1-JzT6PcX4jEZYPE1eyFhira70jYZdW6UQaCs-6LPHdlzoU8wfgpeizgkVRMPdtV6crLRE2B06lyNOqhNgg=w690-h919-no?authuser=0


remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
